UPDATE photos as pp
  INNER JOIN (
    SELECT CONCAT('http://localhost/AdEntifyFacebookApp/web/uploads/photos/users/', owner_id, '/original/', original_url) as new_original_url,
      CONCAT('http://localhost/AdEntifyFacebookApp/web/uploads/photos/users/', owner_id, '/large/', large_url) as new_large_url,
      CONCAT('http://localhost/AdEntifyFacebookApp/web/uploads/photos/users/', owner_id, '/medium/', medium_url) as new_medium_url,
      CONCAT('http://localhost/AdEntifyFacebookApp/web/uploads/photos/users/', owner_id, '/small/', small_url) as new_small_url, id
    FROM photos
  )
  AS p ON p.id = pp.id SET original_url = new_original_url, medium_url = p.new_medium_url, large_url = p.new_large_url, small_url = p.new_small_url


UPDATE brands as bb
  INNER JOIN (
    SELECT
      CONCAT('https://cdn.adentify.com/', large_logo_url) as new_large_url,
      CONCAT('https://cdn.adentify.com/', medium_logo_url) as new_medium_url,
      CONCAT('https://cdn.adentify.com/', small_logo_url) as new_small_url, id
    FROM brands
  )
  AS b ON b.id = bb.id SET medium_logo_url = b.new_medium_url, large_logo_url = b.new_large_url, small_logo_url = b.new_small_url


INSERT INTO `hashtags`(`id`, `name`, `used_count`) VALUES
(null, 'day', 0),
(null, 'dog', 0),
(null, 'drought', 0),
(null, 'economy', 0),
(null, 'education', 0),
(null, 'eyes', 0),
(null, 'f4f', 0),
(null, 'fail', 0),
(null, 'family', 0),
(null, 'fashion', 0),
(null, 'ff', 0),
(null, 'follow', 0),
(null, 'follow4follow', 0),
(null, 'followback', 0),
(null, 'followforfollow', 0),
(null, 'followme', 0),
(null, 'food', 0),
(null, 'friends', 0),
(null, 'fun', 0),
(null, 'funny', 0),
(null, 'Gardening', 0),
(null, 'geek', 0),
(null, 'girl', 0),
(null, 'girls', 0),
(null, 'globalwarming', 0),
(null, 'hair', 0),
(null, 'happy', 0),
(null, 'harrystyles', 0),
(null, 'health', 0),
(null, 'home', 0),
(null, 'hot', 0),
(null, 'igdaily', 0),
(null, 'igers', 0),
(null, 'instacollage', 0),
(null, 'instacool', 0),
(null, 'instadaily', 0),
(null, 'instafollow', 0),
(null, 'instago', 0),
(null, 'instagood', 0),
(null, 'instagramhub', 0),
(null, 'instalike', 0),
(null, 'instalove', 0),
(null, 'instamood', 0),
(null, 'ipad', 0),
(null, 'ipadgames', 0),
(null, 'iphone', 0),
(null, 'iphonegames', 0),
(null, 'iphoneonly', 0),
(null, 'iphonesia', 0),
(null, 'jj', 0),
(null, 'jobs', 0),
(null, 'l4l', 0),
(null, 'life', 0),
(null, 'like', 0),
(null, 'like4like', 0),
(null, 'likeforlike', 0),
(null, 'lol', 0),
(null, 'look', 0),
(null, 'love', 0),
(null, 'loveit', 0),
(null, 'makeup', 0),
(null, 'marketing', 0),
(null, 'me', 0),
(null, 'music', 0),
(null, 'my', 0),
(null, 'nature', 0),
(null, 'news', 0),
(null, 'niallhoran', 0),
(null, 'nice', 0),
(null, 'night', 0),
(null, 'nofilter', 0),
(null, 'ootd', 0),
(null, 'party', 0),
(null, 'People', 0),
(null, 'photo', 0),
(null, 'photography', 0),
(null, 'photooftheday', 0),
(null, 'picoftheday', 0),
(null, 'picstitch', 0),
(null, 'pink', 0),
(null, 'pretty', 0),
(null, 'repost', 0),
(null, 'sales', 0),
(null, 'selfie', 0),
(null, 'shoes', 0),
(null, 'shoutout', 0),
(null, 'sky', 0),
(null, 'smile', 0),
(null, 'socialgood', 0),
(null, 'socialmedia', 0),
(null, 'solar', 0),
(null, 'startup', 0),
(null, 'statigram', 0),
(null, 'style', 0),
(null, 'summer', 0),
(null, 'sun', 0),
(null, 'swag', 0),
(null, 'tagsforlikes', 0),
(null, 'tagsformoney', 0),
(null, 'tbt', 0),
(null, 'tfb', 0),
(null, 'tflers', 0),
(null, 'throwback', 0),
(null, 'throwbackthursday', 0),
(null, 'tired', 0),
(null, 'tweegram', 0),
(null, 'volunteer', 0),
(null, 'wcw', 0),
(null, 'webstagram', 0),
(null, 'Wedding', 0)