imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ 'AdEntifyCommonBundle' ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }


# FosRestBundle
fos_rest:
    view:
        view_response_listener: force
        formats:
            rss:  false
            xml:  false
            json: true
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        mime_types:
            json: ['application/json', 'application/x-json', 'application/vnd.example-com.foo+json']
            rss: 'application/rss+xml'
            jpg: 'image/jpeg'
            png: 'image/png'
    body_listener: true
    param_fetcher_listener: force
    allowed_methods_listener: true
    access_denied_listener:
        json: true
    format_listener:
        default_priorities:
            - html
            - json
            - xml
            - rss
            - "*/*"
            # never reached due to "*/*"
            - ding
        # the subsequent line overrides the following line, so the default is NULL
        fallback_format: json
        fallback_format: ~
        prefer_extension: true
    routing_loader:
        default_format: json
    exception:
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Doctrine\ORM\OptimisticLockException': HTTP_CONFLICT
        messages:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': true

sensio_framework_extra:
    view:    { annotations: false }
    router:  { annotations: true }

# Facebook
fos_facebook:
    alias:  facebook
    app_id: 159587157398776
    secret: 6465372f50a4b1e570cfe4ce7fd62cca
    cookie: true
    permissions: [email, user_birthday, user_photos, friends_photos, read_friendlists]
    culture:     fr_FR

# Twitter
fos_twitter:
    file:
    consumer_key:    mzKZ8anZeGddPOgVWnQ
    consumer_secret: d27XZ9UpNyowFiLpugC1EhC8xwdQlwcwtrkTHIXE
    callback_route:  "_security_check_twitter"

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: AdEntify\CoreBundle\Entity\User

stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            timestampable: true
            sluggable:     true

# Services
services:
    my.facebook.user:
        class: AdEntify\UserBundle\Security\User\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
    my.twitter.user:
        class: AdEntify\UserBundle\Security\User\Provider\TwitterProvider
        arguments:
            twitter_oauth: "@fos_twitter.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
            session: "@session"

# General parameters
parameters:
    contact_email: contact@adentify.com
    from_email:    no-reply@adentify.com

# Instagram
ad_entify_instagram:
    client_id: db51217592cf490aab08224763fc6cea
    client_secret: 48017f2c3cf441d6996ca7813e1abeb9

# OAuth
fos_oauth_server:
    db_driver: orm       # Driver availables: orm, mongodb, or propel
    client_class:        AdEntify\CoreBundle\Entity\OAuth\Client
    access_token_class:  AdEntify\CoreBundle\Entity\OAuth\AccessToken
    refresh_token_class: AdEntify\CoreBundle\Entity\OAuth\RefreshToken
    auth_code_class:     AdEntify\CoreBundle\Entity\OAuth\AuthCode
    service:
        user_provider: fos_user.user_manager

# Flickr
ad_entify_flickr:
    client_id:     370e2e2f28c0ca81fd6a5a336a6e2c89
    client_secret: 6084b60c02b4c8fc

# Imagine
avalanche_imagine:
    filters:
        small:
            type:    thumbnail
            options: { size: [150, 9999], mode: inset, quality: 80 }
        medium:
            type:    thumbnail
            options: { size: [320, 9999], mode: inset, quality: 80 }
        large:
            type:    thumbnail
            options: { size: [1024, 9999], mode: inset, quality: 100 }

# AdEntify Core
ad_entify_core:
    foursquare:
        client_id:     "FTCUYTRQ5C4TMDYBAYB4PVVQEKMSG2HCDYNXKD2MHHURLPEZ"
        client_secret: "1I2D3YVPIN2RFPCMTLER5TROVTTZVBT4KT1ML3PTUBLMFYR1"