ad_entify_flickr:
    resource: "@AdEntifyFlickrBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

ad_entify_instagram:
    resource: "@AdEntifyInstagramBundle/Controller/"
    type:     annotation
    prefix:   /

ad_entify_user:
    resource: "@AdEntifyUserBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

ad_entify_common:
    resource: "@AdEntifyCommonBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        expose: true

# API REST
product:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\ProductsController
    options:
        expose: true

brand:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\BrandsController
    options:
        expose: true

person:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\PeopleController
    options:
        expose: true

tag:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\TagsController
    options:
        expose: true

like:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\LikesController
    options:
        expose: true

comment:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\CommentsController
    options:
        expose: true

photo:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\PhotosController
    options:
        expose: true

oauthuserinfo:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\OAuthUserInfoController
    options:
        expose: true


# OAuth
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# JS Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"