ad_entify_backoffice:
    resource: "@AdEntifyBackofficeBundle/Controller/"
    type:     annotation
    prefix:   /bo-admin

hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /login

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /login

twitter_login:
    pattern: /login/check-twitter

flickr_login:
    pattern: /login/check-flickr

ad_entify_flickr:
    resource: "@AdEntifyFlickrBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

ad_entify_instagram:
    resource: "@AdEntifyInstagramBundle/Controller/"
    type:     annotation
    prefix:   /

ad_entify_user:
    resource: "@AdEntifyUserBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

ad_entify_common:
    resource: "@AdEntifyCommonBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        expose: true

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"

fos_user_security_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    options:
        expose: true

ad_entify_embed_js:
    resource: "@AdEntifyEmbedJsBundle/Controller/"
    type:     annotation
    prefix:   /

# API REST
product:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\ProductsController
    options:
        expose: true

brand:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\BrandsController
    options:
        expose: true

person:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\PeopleController
    options:
        expose: true

tag:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\TagsController
    options:
        expose: true

like:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\LikesController
    options:
        expose: true

comment:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\CommentsController
    options:
        expose: true

photo:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\PhotosController
    options:
        expose: true

oauthuserinfo:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\OAuthUserInfoController
    options:
        expose: true

security:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\SecurityController
    options:
        expose: true

venue:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\VenuesController
    options:
        expose: true

tagStat:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\TagStatsController
    options:
        expose: true

user:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\UsersController
    options:
        expose: true

category:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\CategoriesController
    options:
        expose: true

notification:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\NotificationsController
    options:
        expose: true

setting:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\SettingsController
    options:
        expose: true

action:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\ActionsController
    options:
        expose: true

hashtag:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\HashtagsController
    options:
        expose: true

report:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\ReportsController
    options:
        expose: true

productType:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\ProductTypesController
    options:
        expose: true

# Public Tags REST
public_tag:
    type:     rest
    resource: AdEntify\EmbedJsBundle\Controller\PublicTagsController
    options:
        expose: true

public_photo:
    type:     rest
    resource: AdEntify\EmbedJsBundle\Controller\PublicPhotosController
    options:
        expose: true

# OAuth
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

# JS Routing
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_facebook_channel:
    resource: "@FOSFacebookBundle/Resources/config/routing.xml"

#NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api-doc/

# Upload
upload:
    resource: AdEntify\CoreBundle\Controller\UploadController
    type:     annotation
    prefix:   /
    options:
        expose: true

_imagine:
    resource: .
    type:     imagine