ad_entify_instagram:
    resource: "@AdEntifyInstagramBundle/Controller/"
    type:     annotation
    prefix:   /

ad_entify_user:
    resource: "@AdEntifyUserBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

ad_entify_common:
    resource: "@AdEntifyCommonBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    options:
        expose: true

# API REST
product:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\ProductsController

brand:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\BrandsController

person:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\PeopleController

tag:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\TagsController

like:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\LikesController

comment:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\CommentsController

photo:
    type:     rest
    resource: AdEntify\CoreBundle\Controller\PhotosController

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"