jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_FACEBOOK:    ROLE_USER
        ROLE_TWITTER:     ROLE_USER
        ROLE_TEAM:        ROLE_USER
        ROLE_ANOUNCER:    ROLE_USER
        ROLE_ADMIN:       [ROLE_USER, ROLE_TEAM]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_TEAM, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        api:
            pattern:    ^/api/
            fos_oauth:  true
            stateless:  true
            anonymous:  true
        main:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/
            form_login:                      # On définit notre méthode d'authentification
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                success_handler: adentify_authentication_handler
                failure_handler: adentify_authentication_handler
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                default_target_path: /app/
                login_path:  /
            oauth:
                resource_owners:
                    twitter:         "/login/check-twitter"
                    flickr:          "/login/check-flickr"
                login_path:          fos_user_security_login #loggedInHome
                failure_path:        home_logoff
                oauth_user_provider:
                    service: adentify_user.fos_ub_user_provider
            anonymous:               true
            remember_me:
                key:                 %secret%
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~
            logout:          #true            # On autorise la déconnexion manuelle (désactivé par défaut)
                handlers: ["adentify_fos_facebook.logout_handler"]

    access_control:
        #- { path: ^/app, roles: [ IS_AUTHENTICATED_FULLY ], requires_channel: https }
        #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ], requires_channel: https }
        #- { path: ^/public-api, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], requires_channel: https }
        - { path: ^/bo-admin, roles: [ ROLE_TEAM ] }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ], requires_channel: https }