jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: adentify_user.emailLoginProvider
        my_fos_facebook_provider:
            id: my.facebook.user
        my_fos_twitter_provider:
            id: my.twitter.user

    firewalls:
        login:
            pattern:   ^/(login$|register|resetting)  # Les adresses de ces pages sont login, register et resetting
            anonymous: true                           # On autorise bien évidemment les anonymes sur ces pages !
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
        main:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/.*
            form_login:                      # On définit notre méthode d'authentification
                provider:    fos_userbundle  # On lit l'authentification au provider définit plus haut
                remember_me: true            # On active la possibilité du "Se souvenir de moi" (désactivé par défaut)
                default_target_path: /app/
                login_path:  /
            #fos_facebook:
            #    app_url:             "http://apps.facebook.com/appName/"
            #    server_url:          "http://localhost/AdEntifyFacebookApp/web/"
            #    login_path:          /
            #    check_path:          /facebook/login-check
            #    default_target_path: /app/
            #    provider:            my_fos_facebook_provider
            #    remember_me: true
            oauth:
                resource_owners:
                    twitter:         "/login/check-twitter"
                    flickr:          "/login/check-flickr"
                login_path:          /
                failure_path:        /
                oauth_user_provider:
                    service: adentify_user.fos_ub_user_provider
            anonymous:               true
            remember_me:
                key:                 %secret%
                lifetime: 31536000 # 365 jours en secondes
                path:     /
                domain:   ~
            logout:          #true            # On autorise la déconnexion manuelle (désactivé par défaut)
                handlers: ["adentify_fos_facebook.logout_handler"]

    access_control:
        #- { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
