jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        my_fos_facebook_provider:
            id: my.facebook.user

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    firewalls:
        public:
            # since anonymous is allowed users will not be forced to login
            pattern:   ^/.*
            fos_facebook:
                app_url:             "http://apps.facebook.com/appName/"
                server_url:          "http://localhost/AdEntifyFacebookApp/web/fbApp/"
                #login_path:          /login
                check_path:          /facebook/login_check
                default_target_path: /
                provider:            my_fos_facebook_provider
            anonymous:               true
            remember_me:
                key:                 %secret%
            logout:          #true            # On autorise la déconnexion manuelle (désactivé par défaut)
                handlers: ["adentify_fos_facebook.logout_handler"]

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
