<?php

namespace AdEntify\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * HashtagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HashtagRepository extends EntityRepository
{
    /**
     * Create hashtag if not exist and increment used count
     *
     * @param $name
     * @return Hashtag|object
     */
    public function createIfNotExist($name)
    {
        $name = str_replace(array(' ', '#'), '', trim($name));
        if (is_numeric($name)) {
            return $this->getEntityManager()->getRepository('AdEntifyCoreBundle:Hashtag')->find($name);
        } else {
            $hashtag = $this->findOneBy(array(
                'name' => strtolower($name)
            ));
            if ($hashtag) {
                $hashtag->setUsedCount($hashtag->getUsedCount() + 1);
                $this->getEntityManager()->merge($hashtag);
            } else {
                $hashtag = new Hashtag();
                $hashtag->setName($name)->setUsedCount(1);
                $this->getEntityManager()->persist($hashtag);
            }
        }
        return $hashtag;
    }
}
